spring.application.name=bio7-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://ep-dawn-firefly-aeu0qtyn-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_23UzacFARIXo

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
